### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/danger-swiftlint#1]
Should try linting the plugin.

**Comment by thiagofelix** [comment]
Do you mean lint the ruby code? If yes I think the tool mostly used out there (stats from my head, not serious research) [rubocop](https://github.com/bbatsov/rubocop)

**Comment by ashfurrow** [comment]
Aye! Rubocop was the plan :)

**Comment by mokagio** [comment]
Closed by #61 🎉
