### ISSUE TITLE
Breaks when filename has spaces

### ISSUE THREAD

**Issue by esttorhe** [ashfurrow/danger-swiftlint#13]
e.g.: `Observable + Operations.swift` breaks the plugin

See here: https://travis-ci.org/RxSwiftCommunity/RxViewModel/builds/142914303

<details>
Unrecognized arguments: "Categories/Observable", "+", "Operations.swift"
[!] Invalid `Dangerfile` file: A JSON text must at least contain two octets!. Updating the Danger gem might fix the issue.
 #  from Dangerfile:27
 #  -------------------------------------------
 #  # Run SwiftLint
 swiftlint.lint_files
 #  -------------------------------------------
</details>

I resorted to renaming the file for now but thought it was a good idea to at least bring this issue to light.

**Comment by ashfurrow** [comment]
Should be fixed in #9

**Comment by esttorhe** [comment]
I can confirm it works because i've been using the fork from #9 since i first created this issue 👍 

Thanks
