### ISSUE TITLE
Proposal: Merge into Danger Swift

### ISSUE THREAD

**Issue by orta** [ashfurrow/danger-swiftlint#17]
This is likely to be one of the main reasons people use Danger Swift, I think it makes sense to probably just include in in core to save on some of the expense of Danger plugins ( e.g. #14 ). While I think this can be fixed, I'm not sure if it can be done in an elegant way (danger swift has to be compiled twice if you're not using a `package.swift` for example )

This related to the discussion in https://github.com/danger/swift/issues/139

**Comment by ashfurrow** [comment]
Yup, I followed up in that conversation but the rationale makes total sense to me 👍 Let me know what I can do to help.
