### ISSUE TITLE
Clearer installation instructions

### ISSUE THREAD

**Issue by kylejm** [ashfurrow/danger-swiftlint#20]
It wasn't clear to me that I needed to install `SwiftLint` myself outside of the `danger` and `danger-swiftlint` setup. 

In hindsight this seems obvious. However I wonder if others who are new to Danger (sounds funny) realise they need to do this? 

I had the same problem with `danger-prose` requiring `pip` to be installed on the machine, which I did not realise.

Would you like a PR for your `README.md` to add this explanation/description/instructions? 😄

**Comment by ashfurrow** [comment]
A PR would be very welcome, thanks!
