### ISSUE TITLE
Evaluate if an update of selective linting implementation is needed

### ISSUE THREAD

**Issue by mokagio** [ashfurrow/danger-swiftlint#25]
Now that [the issue in the SwiftLint behaviour](https://github.com/realm/SwiftLint/issues/551) that was [preventing a "direct" implementation of selective linting](https://github.com/ashfurrow/danger-swiftlint/issues/16) has [been fixed](https://github.com/realm/SwiftLint/pull/890) we should re-evaluate way selective linting is implemented.

My guess is that we won't need to generate a dedicated config file on the fly anymore, which should simplify the code a bit. Win!

It could also be an interesting occasion to setup some testing on actual macOS boxes running SwiftLint, to ensure we're actually in line with its behaviour.

**Comment by thiagofelix** [comment]
I was looking into this and found that we don't control much which version of swiftlint will be installed at the user's machine. It would be better if we could control that so we can pin both `danger-swift` and `swiflint` compatible versions together. Eg, if we remove the workaround of selective linting we would need to user to have the latest version of swiftlint, which might not happen be true hence to a flaky behavour.

I will spend some time to see if we can somehow tie together both versions going forward. Meaning if the user installs `danger-swiftlint@x.y` it will be interfacing with `swiftlint@x.y` as well, both using version `x.y`, even better if we could follow swiftlint version cadence and numbering, so it became more predictable what is going to happen when you install.

Do you have any thoughts on that @mokagio ?

**Comment by thiagofelix** [comment]
I think what I am trying to describe/suggest is that we should manage the `swiftlint` installation and make sure our code always works and is released targeting a specific version of it. 

We basically shift from "checking" if the library is installed to "enforcing" such version is installed so that we know it will always works =)

**Comment by thiagofelix** [comment]
I thought about making swiftlint a stricter dependency of danger-swiftlint (maybe having a post-install script here) and sandboxing its installation inside this library scope so we can run it from a know version/place, but looking a swiftlint install process I see it depends on a couple of global system configuration so I am not sure if it will be possible to have a _local_ scoped installation of it. Still digging

**Comment by thiagofelix** [comment]
Hi @mokagio I am closing this due to #28 implementation.
We ended up removing the the temporary config as swiftlint is now fixed.

Thanks and please let me know if you disagree with me closing this =)
