### ISSUE TITLE
SwiftLint 0.17 support

### ISSUE THREAD

**Issue by mokagio** [ashfurrow/danger-swiftlint#33]
On the 24th of March 2017 we got [SwiftLint 0.17](https://github.com/realm/SwiftLint/releases). It has some breaking changes and some new rules. It would be great to support it 😄 .

**Comment by ashfurrow** [comment]
Sounds good to me 👍 I'm very busy this week, so truly any help would be welcome.

**Comment by thiagofelix** [comment]
Awesome to bring this up.
In terms of breaking changes, what exactly is needed from us? 

My understanding reading the docs was that the breaking changes are related to few rules only and not to the CLI (which we call). If that is true then simply bumping swiftlint version would get it done wouldn't it? =)
