### ISSUE TITLE
Files with '+' in their name not being excluded when in excluded paths

### ISSUE THREAD

**Issue by mfclarke** [ashfurrow/danger-swiftlint#39]
If I have a file called say `HomeViewSpec+Rotation.swift` in the excluded folder `UnitTests` and make a change to it in a PR, the plugin will incorrectly lint this file 🤕 

I believe it's the escaping of the `+` which is messing with it. I'll attempt a PR to fix this...

**Comment by ashfurrow** [comment]
Interesting, thanks for opening an issue! A PR would be lovely but if you can't get to it I can take a look next week.

**Comment by mfclarke** [comment]
No worries, turned out to be a simple fix. Nice to do a little bit of ruby again!
