### ISSUE TITLE
Add feature to set SwiftLint execution path

### ISSUE THREAD

**Issue by giginet** [ashfurrow/danger-swiftlint#44]
I integrate SwiftLint via CocoaPods, so `swiftlint` execution path is different than usual.

I want new feature to set SwiftLint path.

https://github.com/ashfurrow/danger-swiftlint/blob/master/ext/swiftlint/swiftlint.rb#L55

**Comment by ashfurrow** [comment]
That makes sense – what can we do to support your use case?

**Comment by marcelofabri** [comment]
I think adding a `attr_accessor :binary_path` and then using it should be enough

**Comment by giginet** [comment]
> what can we do to support your use case?

I submitted #45. Please review this 🙏
