### ISSUE TITLE
0.7.0 out?

### ISSUE THREAD

**Issue by netbe** [ashfurrow/danger-swiftlint#50]
Hi, 

I am getting the following error lately:

```
 ▸ Error loading the plugin `danger-swiftlint-0.7.0`.
[13:33:33]: ▸ Gem::LoadError - can't activate danger-swiftlint-0.7.0, already activated danger-swiftlint-0.6.0
```

I guess I need to upgrade my gemfile but I noticed there was no release/tag for 0.7.0, should I restrict it to 0.6.0?

Thanks

**Comment by marcelofabri** [comment]
Although there's no tag for 0.7.0, that doesn't matter for RubyGems. You can see that it's available: https://rubygems.org/gems/danger-swiftlint/versions/0.7.0.

**Comment by thii** [comment]
@netbe I just pushed a 0.7.0 tag so it should match with the released version on Ruby Gems now.

**Comment by thii** [comment]
I guess this is resolved.
