### ISSUE TITLE
Option to run swiftlint with strict/lenient mode

### ISSUE THREAD

**Issue by Sega-Zero** [ashfurrow/danger-swiftlint#57]
Would like to have an opportunity to run swiftlint in strict or lenient mode. Is there a way to pass an additional commandline parameters?

**Comment by ashfurrow** [comment]
Hmm, tricky. I've looked at the [source code for parsing options](https://github.com/ashfurrow/danger-swiftlint/blob/f290c1861f0739ba2b1726611738a3a8ae6213ca/ext/swiftlint/swiftlint.rb#L38-L54) and you might be able to pass additional arguments by adding as an option like `"lenient" => ""` but we don't expose a way to add arbitrary options to the command invocation. I think we should just add the ability for you to add arbitrary command-line options to `swiftlint`. Would you be interested in adding that feature?

**Comment by Sega-Zero** [comment]
I have no experience in ruby yet :)

**Comment by ashfurrow** [comment]
No worries! If you're keen, try it out, but no pressure. I'll try to get to it sometime this weekend.

**Comment by ashfurrow** [comment]
Okay, this should be good to go. I released the new feature as 0.10.0.
