### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by AvdLee** [ashfurrow/danger-swiftlint#68]
Probably caused by [this](https://github.com/ashfurrow/danger-swiftlint/commit/1368b6606a0549c9306d79f487b750e79493ab53#diff-8779f9203f0e53486f80fde88b1552c9R44) commit, we're now getting errors in our setup:

`fatal error: Could not read configuration file at path '/Users/antoinevanderlee/Documents/GIT-Projects/WeTransfer/Coyote/Coyote/Views/Bucket/BucketViewController.swift/Submodules/Rabbit/.swiftlint.yml': file /Users/marcelofabri/Westfield/SwiftLint/Source/SwiftLintFramework/Models/Configuration.swift, line 167`

It seems to be expecting a config file for each file specific, where we used the `config_file` to reuse a config file from our submodule.

What is the reason for this change @ashfurrow? Any new changes on how to use the config file path now?

**Update**
I can verify our setup is working with the 0.9.0 release from before. Our config:

```
# Run SwiftLint
swiftlint.config_file = "Submodules/Rabbit/.swiftlint.yml"
swiftlint.lint_files inline_mode: true
```

**Comment by ashfurrow** [comment]
Sorry about that! I'm glad you have a workaround in place in the mean time.

I agree that is the likely issue. I think what's happening is that the config path is being expanded from the directory that swiftlint is being run from. Maybe specifying an absolute path would work. I'm not sure.

I'm really swamped at work and don't have time to look at this right now – any help or pull requests you're able to provide would be a huge help!

**Comment by AvdLee** [comment]
@ashfurrow opened up a PR for this: https://github.com/ashfurrow/danger-swiftlint/pull/69
